name: Run Tests Before Push

on:
  push:
    branches:
      - master  # Adjust to your target branch
  pull_request:
    branches:
      - master  # Adjust to your target branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Use the version of Node.js you're working with

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
        continue-on-error: false
